app = "trainvision-backend"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  GEMINI_MODEL = "gemini-2.5-flash"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/ai/status"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256