name: CI - Test TrainVision AI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements-render.txt
    
    - name: Install frontend dependencies
      run: |
        cd rail-frontend
        npm ci
    
    - name: Build frontend
      run: |
        cd rail-frontend
        npm run build
    
    - name: Test backend imports
      run: |
        cd backend
        python -c "import main_lite; print('✅ Backend imports successfully')"
    
    - name: Test frontend build
      run: |
        cd rail-frontend
        ls -la dist/
        echo "✅ Frontend build successful"